const char* g_u8RepoString[] = {
	R"###(---->RepoInfo: )###",
	R"###(Modify Rev : 2507)###",
	R"###(Modify Date: 2017-08-11 16:11:08 +0800)###",
	R"###(Top    Rev : 2509)###",
	R"###(Repo   Path: ^/main/branches/DrVoice_ReqOpt_vs2015)###",
	R"###(Local  Path: C:\SVN\DrVoice_ReqOpt_vs2015)###",
	"",
	R"###(---->FileChangeList: )###",
	R"###(*) Pub\libTelParser)###",
	R"###(*) WS_Server\ServerConst.cpp)###",
	R"###(+) Pub\Common\a)###",
	R"###(+) Pub\MongoAccess\MongocHelp.h2)###",
	"",
};
